2020-10-14 22:29:58,426 INFO: Microblog startup [in /home/mat/Documents/dev/projets/flask_blog/app/__init__.py:44]
2020-10-14 22:55:38,394 INFO: Microblog startup [in /home/mat/Documents/dev/projets/flask_blog/app/__init__.py:44]
2020-10-14 22:55:45,033 INFO: Microblog startup [in /home/mat/Documents/dev/projets/flask_blog/app/__init__.py:44]
2020-10-14 22:56:11,392 INFO: Microblog startup [in /home/mat/Documents/dev/projets/flask_blog/app/__init__.py:44]
2020-10-15 22:05:26,183 INFO: Microblog startup [in /home/mat/Documents/dev/projets/flask_blog/app/__init__.py:44]
2020-10-15 22:06:41,870 INFO: Microblog startup [in /home/mat/Documents/dev/projets/flask_blog/app/__init__.py:44]
2020-10-15 22:07:23,450 INFO: Microblog startup [in /home/mat/Documents/dev/projets/flask_blog/app/__init__.py:44]
2020-10-15 22:08:01,291 INFO: Microblog startup [in /home/mat/Documents/dev/projets/flask_blog/app/__init__.py:44]
2020-10-15 22:08:38,100 INFO: Microblog startup [in /home/mat/Documents/dev/projets/flask_blog/app/__init__.py:44]
2020-10-15 22:09:33,459 INFO: Microblog startup [in /home/mat/Documents/dev/projets/flask_blog/app/__init__.py:44]
2020-10-15 22:09:42,121 INFO: Microblog startup [in /home/mat/Documents/dev/projets/flask_blog/app/__init__.py:44]
2020-10-15 22:41:41,415 INFO: Microblog startup [in /home/mat/Documents/dev/projets/flask_blog/app/__init__.py:44]
2020-10-15 22:41:49,022 INFO: Microblog startup [in /home/mat/Documents/dev/projets/flask_blog/app/__init__.py:44]
2020-10-15 22:42:05,968 ERROR: Exception on /user/mathieu [GET] [in /home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mat/Documents/dev/projets/flask_blog/app/routes.py", line 77, in user
    form = EmptyForm()
NameError: name 'EmptyForm' is not defined
2020-10-15 22:43:03,016 INFO: Microblog startup [in /home/mat/Documents/dev/projets/flask_blog/app/__init__.py:44]
2020-10-15 22:43:38,845 ERROR: Exception on /user/mathieu [GET] [in /home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mat/Documents/dev/projets/flask_blog/app/routes.py", line 78, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mat/Documents/dev/projets/flask_blog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/mat/Documents/dev/projets/flask_blog/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/mat/Documents/dev/projets/flask_blog/app/templates/user.html", line 12, in block "content"
    <p>{{ user.followers.count() }} followers, {{ user.folloed.count() }} following.</p>
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'app.models.User object' has no attribute 'folloed'
2020-10-15 22:44:31,400 INFO: Microblog startup [in /home/mat/Documents/dev/projets/flask_blog/app/__init__.py:44]
2020-10-15 22:44:52,948 ERROR: Exception on /user/caro [GET] [in /home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "/home/mat/Documents/dev/projets/flask_blog/app/routes.py", line 78, in user
    return render_template('user.html', user=user, posts=posts, form=form)
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/home/mat/Documents/dev/projets/flask_blog/venv/lib/python3.6/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "/home/mat/Documents/dev/projets/flask_blog/app/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/mat/Documents/dev/projets/flask_blog/app/templates/base.html", line 32, in top-level template code
    {% block content %}{% endblock %}
  File "/home/mat/Documents/dev/projets/flask_blog/app/templates/user.html", line 18, in block "content"
    {{ form.hidden_tags() }}
jinja2.exceptions.UndefinedError: 'app.forms.EmptyForm object' has no attribute 'hidden_tags'
2020-10-15 22:45:37,836 INFO: Microblog startup [in /home/mat/Documents/dev/projets/flask_blog/app/__init__.py:44]
